# Generated by Django 2.1.7 on 2019-04-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFilm', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('director', models.CharField(max_length=100)),
            ],
        ),
    ]
