# Generated by Django 2.1.7 on 2019-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='sl10.Categoria'),
        ),
    ]
