# Generated by Django 2.1.7 on 2019-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl10', '0002_auto_20190425_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descrizione',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
