# Generated by Django 2.1.7 on 2019-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl10', '0003_auto_20190425_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('date_born', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='tipo',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='categorie',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descrizione',
        ),
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.TextField(default=1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, to='sl10.Attore'),
        ),
        migrations.AddField(
            model_name='film',
            name='immages',
            field=models.ManyToManyField(blank=True, to='sl10.Immagine'),
        ),
        migrations.AddField(
            model_name='film',
            name='languages',
            field=models.ManyToManyField(blank=True, to='sl10.Lingua'),
        ),
    ]
